### ISSUE TITLE
Move Infrastructure to Scale

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/GoAPI#43] opened 2015-04-27 19:01 UTC
So this is going to more of a server TODO that involves [GoAPI](https://github.com/curt-labs/GoAPI), [v2Mock](https://github.com/curt-labs/v2Mock), [GoAdmin](https://github.com/curt-labs/GoAdminK), [GoSurvey](https://github.com/curt-labs/GoSurvey), [GoReports](https://github.com/curt-labs/GoReports), [CartIntegration](https://github.com/curt-labs/CartIntegration), [HitchInfo - Final](https://github.com/curt-labs/HitchInfoFinal), and [HitchInfo](https://github.com/curt-labs/HitchInfo).

=======

#### Structure

Currently it is setup on 4 static servers that run each application in a docker container with NGINX doing a reverse proxy route to each application....this is not ideal.

We would like the server structure to be more scalable using either [Instance Groups](https://cloud.google.com/compute/docs/instance-groups/) or [GKE](https://cloud.google.com/container-engine/docs/). I'd like to try and stay away from raw [Kubernetes](http://kubernetes.io) just because it can be a pain to move a cluster configuration across different client machines.

##### Proxy
So a tricky part of doing this is going to be how to proxy to the scalable instances. I started creating an NGINX docker container that will work as a reverse proxy load balancer; it will take the request for api.curtmfg.com and route the request to the proper HTTP load balancer for that application.

=======

#### Deployment

Deployment will need to be done using a Jenkins instance with the same type of shell script that was done for [TrucksPlus API](https://github.com/aries-auto/trucksplusapi). Currently the shell script for the TrucksPlus API is not zero downtime, it's pretty close, but it needs to be absolutely zero, we don't want to be taking down API's for deployment.

**Comment by mickelsonm** [comment] 2015-04-27 19:31
Ideas if you go with the instance group route:

The deployment script I wrote for TrucksPlus' API could be enhanced to include HTTPS (port 443). I think this will include:

* adding a forwarding rule for port 443 (https)
* adding an https-server firewall tag, which can be assigned to the instance template at the time it is created
* adding associated https-health-checks (maybe?)
* ... might be more to follow ...

Application changes:

* update dockerfiles to also expose port 443
* add TLS/HTTPS support on the actual http server

Centralizing digital assets:

* place ssl certificates in a place where they are accessible for apps

**Comment by DavidVaini** [comment] 2015-04-27 20:18
In regarding the downtime, I think the issue is that it creates new instances, and while those are being built and are "not healthy" it is deleting all the existing healthy ones. Thus a small gap of downtime.

I think idealy, it would  get the IP addresses of all the existing instances,  create the new ones, and make a curl request every 30 seconds against the new IP addresses of the instance to a health check page, if the instance returns status 200 (meaning the site works on that instance), then "delete" the old instances.

**Comment by ninnemana** [comment] 2015-04-27 20:50
The beginnings of some of this are [here](https://console.developers.google.com/project/curt-groups)

**Comment by ninnemana** [comment] 2015-04-27 20:53
@DavidVaini, first place I would look would be  at the `Handling Unhealthy Instances` section [here](https://cloud.google.com/compute/docs/load-balancing/health-checks#handling_unhealthy_instances)

**Comment by ninnemana** [comment] 2015-04-27 21:03
The reverse proxy - nginx aspect I was referencing has been started [here](https://github.com/curt-labs/manifests/tree/master/kubernetes/app-group)

**Comment by DavidVaini** [comment] 2015-05-12 21:27
All of the previous assets have been moved over to Instance Groups. They are all hooked up with Jenkins, HTTPS is not configured yet.

**Comment by ninnemana** [comment] 2015-05-13 04:54
Looks like everything is running fine on the instance groups, I ran a benchmark on v2mock for the Instance Group implementation and the current setup

##### Current Setup
![image](https://cloud.githubusercontent.com/assets/187030/7603989/e513daaa-f901-11e4-96cb-fb107fe879c9.png)

#### Instance Groups
![image](https://cloud.githubusercontent.com/assets/187030/7604001/2511f1d2-f902-11e4-99d6-3396b9b47a9d.png)

**Comment by DavidVaini** [comment] 2015-05-13 13:34
Update, so now that https is setup, comes the testing. Currently there may be an issue with 4 emails being sent out for one report.

**Comment by DavidVaini** [comment] 2015-05-13 13:45
I just tested GoReports, I ran 5 different loadsheets, and only got one email per loadsheet.

**Comment by DavidVaini** [comment] 2015-05-19 13:48
v2mock was moved over and was the last one, I am going to mark this issue as completed.

**Comment by mickelsonm** [comment] 2015-05-26 16:34
There's something strange going on with the deployment of v2Mock, which of course is causing some troubles for our main website.

`healthy instance count is: 9 / 8`

And of course it is hanging there.

**Comment by DavidVaini** [comment] 2015-05-26 17:20
The date for the last uploaded on the deploy script in cloud storage looked to be old, I updated the deploy file to the newest one, I just wrap a deployment and it worked, so until further notice I am going to close this issue.

**Closed by DavidVaini** 2015-05-26 17:20 UTC
Labels: enhancement
